name: Simple Cross-Browser Testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cross-browser-tests:
    runs-on: macos-latest  # Required for Safari
    strategy:
      matrix:
        browser: [chrome, firefox, safari]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Browsers (if necessary)
      if: matrix.browser == 'chrome' || matrix.browser == 'firefox'
      run: |
        if [[ "${{ matrix.browser }}" == "chrome" ]]; then
          brew install --cask google-chrome
        elif [[ "${{ matrix.browser }}" == "firefox" ]]; then
          brew install --cask firefox
        fi

    - name: Run simple tests
      run: |
        echo "Testing with ${{ matrix.browser }}"
        case ${{ matrix.browser }} in
          chrome)
            open -a "Google Chrome" "http://example.com"
            ;;
          firefox)
            open -a "Firefox" "http://example.com"
            ;;
          safari)
            open -a "Safari" "http://example.com"
            ;;
        esac
        sleep 10  # Simulate a wait for manual verification or automated interaction
