name: Simple Cross-Browser Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  browser-tests:
    runs-on: macos-latest  # Required for Safari
    strategy:
      matrix:
        browser: [chrome, firefox, safari]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Test ${{ matrix.browser }}
      run: |
        echo "Testing on ${{ matrix.browser }}"
        case ${{ matrix.browser }} in
          chrome)
            open -a "Google Chrome" "http://example.com"
            ;;
          firefox)
            open -a "Firefox" "http://example.com"
            ;;
          safari)
            open -a "Safari" "http://example.com"
            ;;
        esac
        echo "$BROWSER launched successfully!"
